---
include:
#  - board: nice_nano_v2
#    shield: kyria_left
#  - board: nice_nano_v2
#    shield: kyria_right
#  - board: nice_nano_v2
#    shield: settings_reset

  # Kyria MX
  - board: nice_nano_v2
    shield: kyria_rev3_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: kyria_rev3_right nice_view_adapter nice_view

  # Kyria LP Choc
  # - board: nice_nano_v2
  #   shield: kyria_rev3_left
  # - board: nice_nano_v2
  #   shield: kyria_rev3_right
  # - board: nice_nano_v2
  #   shield: settings_reset
